baseurl = "https://kdandia.github.io"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Welcome To My Blog!"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "dandia@usc.edu"

	profilepic = "img/profile.jpg"
	
themesdir = "../.."
	title = "Karina Dandia"
	subtitle = "MY HUGO BLOG"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/kdandia""
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com""
	
	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
